INSERT IGNORE INTO C VALUES

('Built-in Data Types','','','',1,200),
('Varibles','','','',2,200),
('Primitive','',' ','',3,200),
('Integers','Whole numbers','type variableName = value','int x = 5',4,200),
('Floating point','Decimal numbers','','float x = 3.14',5,200),
('Char','Multiple or single character, based of ASCII code','',char c = 'M',6,200),
('Boolean','True / False','','bool A = true',7,200),
('String','NULL','','NULL',8,200),
('Null','N/A','','int x = NULL',9,200),
('Atom','not in standard C','_Atomic ( type-name )','_Atomic int p1',10,200),
('','','','',11,200),
('Structured','','','',12,200),
('Lists','Standard C doesnt support lists','Null','Null',13,200),
('Sets','Standard C doesnt support sets','Null','Null',14,200),
('Vectors','Standard C doesnt support vectors','Null','Null',15,200),
('Maps','','','',16,200),
('hashed map','Standard C doesnt support hashed map','Null','Null',17,200),
('sorted map','','','',18,200),
('','','','',19,200),
('','','','',20,200),
('','','','',21,200),
('Functions','','','',22,200),
('Regular','','void myFunction() {}',23,200),
('Anonymous','Standard C does not support anonymous functions','N/A','N/A',24,200),
('Multiple Arguments','',' myFunction(value1, value2, ... , value n) ',' Add(10, 5, 2)',25,200),
('Variadic','functions that can take a variable number of arguments','int funcName(data_type variable_name, ...)','int funcName(int n, ...) {}',26,200),
('Higher Order','a function that accepts other functions as arguments or returns a function itself.Can be implemented in C using function pointers and compiler support ','void functionName(void(Function pointer)(void)) {}','void myFunc(void (*funcParameter)(void) ){}',27,200),
('If - else','','if (condition) {} else {}','if (x > y) {}',28,200),
('Switch Statement','','switch(expression) {}','{}',29,200),
('Loops','','','',30,200),
('While','','while (condition) {}','{}',31,200),
('Do While','','','',32,200),
('For','','for (statement 1 statement 2 statement 3) {}','',33,200),
('','','','',34,200),
('','','','',35,200),
('','','','',36,200),
('Parameter','','','',37,200),
('Single','','returnType functionName(parameter1) {}','void myName(char name[]) {}',38,200),
('Multiple','','returnType functionName(parameter1, parameter2, parameter3) {}','void myValue(int a, int b, int c) {}',39,200),
('Abitrary','','return type functionName(int, ... ) {}','void value(int a, ..) {}',40,200),
('','','','',41,200),
('Return Mechanism','If you want the function to return a value, you can use a data type.','returnType functionName(parameter1, ...,) {return returnvalue}','return a + b',42,200)
;