INSERT IGNORE INTO HTML VALUES
('Built-in Data Types','','','',1,900),
('Elements','','','',2,900),
('Pragraphs','Add a paragraph to your website.','<p>//value </p>','<p>A paragraph.</p>',3,900),
('Images','Link images to your website.','<img src= //path alt= //description >','<img src= "my_Pic.jpg" alt= "this is my picture." >',4,900),
('Links','Link a clickable link to your website.','<a href= //website_link >//text</a>','<a href="https://www.WolfGangTeam.com">My Link</a>',5,900),
('Headers','Add a header to your website.','<h1>//text</h1> (up to h6)','<h1>My Header</h1>',6,900),
('Footers','Add a footer to your website.','<footer>//text</footer>','<footer>My Footer</footer>',7,900),
('Titles','What is displayed at the top of the browser tab.','<title>//text</title>','<title>My Website</title>',8,900),
('Favicon','Image displayed next to title. Must add the link code right after the title element.','<title></title><link rel="icon" type="image/x-icon" href= //link>','<title></title><link rel="icon" type="image/x-icon" href= "/images/myFavicon.ico">',9,900),
('Colors','Add color to your element. Must be stated within the elements declaration.','<h1 style=//color>//text</h1>','<h1 style="background-color:Red;">Hello, World!</h1>',10,900),
('','','','',11,900),
('Structured','','','',12,900),
('Lists','List that groups a set of related items.','Unordered List: <ul> <li> //value </li> <li> //value </li> <li> //value </li> </ul> Ordered List: The same as unordered list but instead of using <ul></ul> you use <ol></ol>','<ul> <li> A </li> <li> B </li> <li> C </li> </ul>',13,900),
('Table','A table consisting if information between rows and columns.','<table> <tr> <th> //value </th> </tr> <tr> <th> //value </th> </tr> <tr> <th> //value </th> </tr> </table>','<table> <tr> <th> A </th> </tr> <tr> <th>B </th> </tr> <tr> <th> C </th> </tr> </table>',14,900),
('Maps','N/A','N/A','N/A',15,900),
('hashed map','N/A','N/A','N/A',16,900),
('sorted map','N/A','N/A','N/A',17,900),
('','','','',18,900),
('','','','',19,900),
('','','','',20,900),
('Functions','','','',21,900),
('Regular','N/A','','',22,900),
('Anonymous','','','',23,900),
('Multiple Arguments','','','',24,900),
('Variadic','','','',25,900),
('Higher Order','','','',26,900),
('Loops','','','',27,900),
('If - else','','','',28,900),
('While','','','',29,900),
('Do While','','','',30,900),
('For','','','',31,900),
('Case','','','',32,900),
('','','','',33,900),
('','','','',34,900),
('','','','',35,900),
('Parameter','','','',36,900),
('Single','N/A','','',37,900),
('Multiple','','','',38,900),
('Abitrary','','','',39,900),
('','','','',40,900),
('Return Mechanism','','','',41,900)
;
